default:
	mkdir -p build/classes;
	javac -classpath java_cup.jar -sourcepath src -d build/classes src/polyglot/util/*.java src/edu/cornell/cs/cs4120/util/*.java src/edu/cornell/cs/cs4120/xic/ir/*.java src/edu/cornell/cs/cs4120/xic/ir/interpret/*.java src/edu/cornell/cs/cs4120/xic/ir/parse/*.java src/edu/cornell/cs/cs4120/xic/ir/interpret/Main.java;
	# java -cp java_cup.jar:build/classes edu.cornell.cs.cs4120.xic.ir.interpret.Main "test.txt"

